# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bf8c3007d7d1d127e1a4946459b937131dc32e154380c0211a75973525c4fa7ed9fa86bff6f89bcc04e3572feaff8d8e7ff9647569c7f162331097e0ec7d166

test:
  secret_key_base: cba3626102008fd73da2229e9ce9dc51d31e46d860368904b1f7202cd0425b9dfba42661e873e62da9be3a8b058c1175f59f5530e4bb0fc4a9ca7292965a0704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
